version: '3.8'
services:
  vfd-control:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MODBUS_HOST=192.168.1.111
      - MODBUS_PORT=502
    restart: unless-stopped